services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    branch: main
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: your-laravel-key
      - key: DB_CONNECTION
        value: mysql
